// frontend/src/components/widgets/inputs/CheckboxInput.vue
<template>
	<LayoutRow class="checkbox-input">
		<input type="checkbox" :id="`checkbox-input-${id}`" :checked="checked" @change="(e) => $emit('update:checked', (e.target as HTMLInputElement).checked)" />
		<label :for="`checkbox-input-${id}`" tabindex="0" @keydown.enter="(e) => toggleCheckboxFromLabel(e)" :title="tooltip">
			<LayoutRow class="checkbox-box">
				<IconLabel :icon="icon" />
			</LayoutRow>
		</label>
	</LayoutRow>
</template>

<style lang="scss">
.checkbox-input {
	flex: 0 0 auto;
	align-items: center;

	input {
		display: none;
	}

	label {
		display: flex;
		height: 16px;
		// Provides rounded corners for the :focus outline
		border-radius: 2px;

		.checkbox-box {
			flex: 0 0 auto;
			background: var(--color-e-nearwhite);
			padding: 2px;
			border-radius: 2px;

			.icon-label {
				fill: var(--color-2-mildblack);
			}
		}

		&:hover .checkbox-box {
			background: var(--color-f-white);
		}
	}

	input:checked + label {
		.checkbox-box {
			background: var(--color-accent);

			.icon-label {
				fill: var(--color-f-white);
			}
		}

		&:hover .checkbox-box {
			background: var(--color-accent-hover);
		}
	}
}
</style>

<script lang="ts">
import { defineComponent, type PropType } from "vue";

import { type IconName } from "@/utility-functions/icons";

import LayoutRow from "@/components/layout/LayoutRow.vue";
import IconLabel from "@/components/widgets/labels/IconLabel.vue";

export default defineComponent({
	emits: ["update:checked"],
	props: {
		checked: { type: Boolean as PropType<boolean>, default: false },
		icon: { type: String as PropType<IconName>, default: "Checkmark" },
		tooltip: { type: String as PropType<string | undefined>, required: false },
	},
	data() {
		return {
			id: `${Math.random()}`.substring(2),
		};
	},
	methods: {
		isChecked() {
			return this.checked;
		},
		toggleCheckboxFromLabel(e: KeyboardEvent) {
			const target = (e.target || undefined) as HTMLLabelElement | undefined;
			const previousSibling = (target?.previousSibling || undefined) as HTMLInputElement | undefined;
			previousSibling?.click();
		},
	},
	components: {
		IconLabel,
		LayoutRow,
	},
});
</script>

// frontend-svelte/src/components/widgets/inputs/CheckboxInput.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";

	import { type IconName } from "@/utility-functions/icons";

	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import IconLabel from "@/components/widgets/labels/IconLabel.svelte";

	// emits: ["update:checked"],

	export let checked = false;
	export let disabled = false;
	export let icon: IconName = "Checkmark";
	export let tooltip: string | undefined = undefined;

	let id = `${Math.random()}`.substring(2);

	$: displayIcon = (!checked && icon === "Checkmark" ? "Empty12px" : icon) as IconName;

	export function isChecked() {
		return checked;
	}

	function toggleCheckboxFromLabel(e: KeyboardEvent) {
		const target = (e.target || undefined) as HTMLLabelElement | undefined;
		const previousSibling = (target?.previousSibling || undefined) as HTMLInputElement | undefined;
		previousSibling?.click();
	}
</script>

<LayoutRow class="checkbox-input">
	<input type="checkbox" id={`checkbox-input-${id}`} {checked} on:change={(e) => createEventDispatcher("update:checked", e.target.checked)} {disabled} tabindex={disabled ? -1 : 0} />
	<label class:disabled class:checked for={`checkbox-input-${id}`} on:keydown={(e) => e.key === "Enter" && toggleCheckboxFromLabel(e)} title={tooltip}>
		<LayoutRow class="checkbox-box">
			<IconLabel icon={displayIcon} />
		</LayoutRow>
	</label>
</LayoutRow>

<style lang="scss" global>
	.checkbox-input {
		flex: 0 0 auto;
		align-items: center;

		input {
			// We can't use `display: none` because it must be visible to work as a tabbale input that accepts a space bar actuation
			width: 0;
			height: 0;
			margin: 0;
			opacity: 0;
		}

		// Unchecked
		label {
			display: flex;
			height: 16px;
			// Provides rounded corners for the :focus outline
			border-radius: 2px;

			.checkbox-box {
				flex: 0 0 auto;
				background: var(--color-5-dullgray);
				padding: 2px;
				border-radius: 2px;

				.icon-label {
					fill: var(--color-8-uppergray);
				}
			}

			// Hovered
			&:hover .checkbox-box {
				background: var(--color-6-lowergray);
			}

			// Disabled
			&.disabled .checkbox-box {
				background: var(--color-4-dimgray);
			}
		}

		// Checked
		input:checked + label {
			.checkbox-box {
				background: var(--color-e-nearwhite);

				.icon-label {
					fill: var(--color-2-mildblack);
				}
			}

			// Hovered
			&:hover .checkbox-box {
				background: var(--color-f-white);
			}

			// Hovered
			&.disabled .checkbox-box {
				background: var(--color-8-uppergray);
			}
		}
	}
</style>
