// frontend-svelte/src/lib/components/widgets/inputs/TextAreaInput.vue
<template>
	<FieldInput
		:textarea="true"
		class="text-area-input"
		:class="{ 'has-label': label }"
		:label="label"
		:spellcheck="true"
		:disabled="disabled"
		:tooltip="tooltip"
		v-model:value="inputValue"
		@textFocused="() => onTextFocused()"
		@textChanged="() => onTextChanged()"
		@cancelTextChange="() => onCancelTextChange()"
		ref="fieldInput"
	></FieldInput>
</template>

<style lang="scss" global></style>

<script lang="ts">


import FieldInput from "$lib/components/widgets/inputs/FieldInput.svelte";

export default defineComponent({
	emits: ["update:value", "commitText"],
	props: {
		value: { type: String as PropType<string>, required: true },
		label: { type: String as PropType<string>, required: false },
		disabled: { type: Boolean as PropType<boolean>, default: false },
		tooltip: { type: String as PropType<string | undefined>, required: false },
	},
	data() {
		return {
			editing: false,
		};
	},
	computed: {
		inputValue: {
			get() {
				return this.value;
			},
			set(value: string) {
				this.$emit("update:value", value);
			},
		},
	},
	methods: {
		onTextFocused() {
			this.editing = true;
		},
		// Called only when `value` is changed from the <textarea> element via user input and committed, either
		// via the `change` event or when the <input> element is unfocused (with the `blur` event binding)
		onTextChanged() {
			// The `unFocus()` call in `onCancelTextChange()` causes itself to be run again, so this if statement skips a second run
			if (!this.editing) return;

			this.onCancelTextChange();

			// TODO: Find a less hacky way to do this
			const inputElement = this.$refs.fieldInput as typeof FieldInput | undefined;
			if (!inputElement) return;
			this.$emit("commitText", inputElement.getInputElementValue());

			// Required if value is not changed by the parent component upon update:value event
			inputElement.setInputElementValue(this.value);
		},
		onCancelTextChange() {
			this.editing = false;

			(this.$refs.fieldInput as typeof FieldInput | undefined)?.unFocus();
		},
	},
	components: { FieldInput },
});
</script>

// frontend-svelte/src/components/widgets/inputs/TextAreaInput.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";

	import FieldInput from "@/components/widgets/inputs/FieldInput.svelte";

	const dispatch = createEventDispatcher<{ commitText: string }>();

	// emits: ["update:value", "commitText"],

	export let value: string;
	export let label: string | undefined = undefined;
	export let tooltip: string | undefined = undefined;
	export let disabled = false;

	let fieldInput: FieldInput;
	let editing = false;
	let inputValue = value;

	$: createEventDispatcher("update:value", inputValue);

	function onTextFocused() {
		editing = true;
	}

	// Called only when `value` is changed from the <textarea> element via user input and committed, either
	// via the `change` event or when the <input> element is unfocused (with the `blur` event binding)
	function onTextChanged() {
		// The `unFocus()` call in `onCancelTextChange()` causes itself to be run again, so this if statement skips a second run
		if (!editing) return;

		onCancelTextChange();

		// TODO: Find a less hacky way to do this
		dispatch("commitText", fieldInput.getInputElementValue());

		// Required if value is not changed by the parent component upon update:value event
		fieldInput.setInputElementValue(value);
	}

	function onCancelTextChange() {
		editing = false;

		fieldInput.unFocus();
	}
</script>

<FieldInput
	textarea={true}
	class="text-area-input"
	classes={{
		// TODO: Svelte: check if this should be based on `Boolean(label)` or `label !== ""`
		"has-label": Boolean(label),
	}}
	{label}
	{disabled}
	{tooltip}
	spellcheck={true}
	bind:value={inputValue}
	on:textFocused={onTextFocused}
	on:textChanged={onTextChanged}
	on:cancelTextChange={onCancelTextChange}
	bind:this={fieldInput}
/>

<style lang="scss" global></style>
