// client/web/src/components/window/title-bar/TitleBar.vue
<template>
	<div class="header-third">
		<WindowButtonsMac :maximized="maximized" v-if="platform === ApplicationPlatform.Mac" />
		<MenuBarInput v-if="platform !== ApplicationPlatform.Mac" />
	</div>
	<div class="header-third">
		<WindowTitle :title="`${documents.title}${documents.unsaved ? '*' : ''} - Graphite`" />
	</div>
	<div class="header-third">
		<WindowButtonsWindows :maximized="maximized" v-if="platform === ApplicationPlatform.Windows || platform === ApplicationPlatform.Linux" />
		<WindowButtonsWeb :maximized="maximized" v-if="platform === ApplicationPlatform.Web" />
	</div>
</template>

<style lang="scss">
.header-third {
	display: flex;
	flex: 1 1 100%;

	&:nth-child(1) {
		justify-content: flex-start;
	}

	&:nth-child(2) {
		justify-content: center;
	}

	&:nth-child(3) {
		justify-content: flex-end;
	}
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import WindowTitle from "@/components/window/title-bar/WindowTitle.vue";
import WindowButtonsWindows from "@/components/window/title-bar/WindowButtonsWindows.vue";
import WindowButtonsMac from "@/components/window/title-bar/WindowButtonsMac.vue";
import WindowButtonsWeb from "@/components/window/title-bar/WindowButtonsWeb.vue";
import MenuBarInput from "@/components/widgets/inputs/MenuBarInput.vue";
import { ApplicationPlatform } from "@/components/window/MainWindow.vue";

export default defineComponent({
	inject: ["documents"],
	props: {
		platform: { type: String, required: true },
		maximized: { type: Boolean, required: true },
	},
	data() {
		return {
			ApplicationPlatform,
		};
	},
	components: {
		MenuBarInput,
		WindowTitle,
		WindowButtonsWindows,
		WindowButtonsMac,
		WindowButtonsWeb,
	},
});
</script>

// frontend-svelte/src/components/window/title-bar/TitleBar.svelte
<script lang="ts" context="module">
	export type Platform = "Windows" | "Mac" | "Linux" | "Web";
</script>

<script lang="ts">
	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import MenuBarInput from "@/components/widgets/inputs/MenuBarInput.svelte";
	import WindowButtonsMac from "@/components/window/title-bar/WindowButtonsMac.svelte";
	import WindowButtonsWeb from "@/components/window/title-bar/WindowButtonsWeb.svelte";
	import WindowButtonsWindows from "@/components/window/title-bar/WindowButtonsWindows.svelte";
	import WindowTitle from "@/components/window/title-bar/WindowTitle.svelte";

	export let platform: Platform;
	export let maximized: boolean;

	// inject: ["portfolio"],

	$: docIndex = portfolio.state.activeDocumentIndex;
	$: displayName = portfolio.state.documents[docIndex]?.displayName || "";
	$: windowTitle = `${displayName}${displayName && " - "}Graphite`;
</script>

<LayoutRow class="title-bar">
	<LayoutRow class="header-part">
		{#if platform === "Mac"}
			<WindowButtonsMac {maximized} />
		{:else}
			<MenuBarInput />
		{/if}
	</LayoutRow>
	<LayoutRow class="header-part">
		<WindowTitle text={windowTitle} />
	</LayoutRow>
	<LayoutRow class="header-part">
		{#if platform === "Windows" || platform === "Linux"}
			<WindowButtonsWindows {maximized} />
		{:else if platform === "Web"}
			<WindowButtonsWeb />
		{/if}
	</LayoutRow>
</LayoutRow>

<style lang="scss" global>
	.title-bar {
		height: 28px;
		flex: 0 0 auto;

		.header-part {
			flex: 1 1 100%;

			&:nth-child(1) {
				justify-content: flex-start;
			}

			&:nth-child(2) {
				justify-content: center;
			}

			&:nth-child(3) {
				justify-content: flex-end;
			}
		}
	}
</style>
