// frontend-svelte/src/lib/components/window/workspace/Workspace.svelte
<script lang="ts">
  import DialogModal from "$lib/components/floating-menus/DialogModal.svelte";
  import LayoutCol from "$lib/components/layout/LayoutCol.svelte";
  import LayoutRow from "$lib/components/layout/LayoutRow.svelte";
  import Panel from "$lib/components/window/workspace/Panel.svelte";

  const MIN_PANEL_SIZE = 100;
  const PANEL_SIZES = {
    /**/ root: 100,
    /*   ├── */ content: 80,
    /*   │      ├── */ document: 60,
    /*   │      └── */ graph: 40,
    /*   └── */ details: 20,
    /*          ├── */ properties: 45,
    /*          └── */ layers: 55,
  };

  let panelSizes = PANEL_SIZES;
  let documentPanel: Panel;

  $: activeDocumentIndex = portfolio.state.activeDocumentIndex;
  $: nodeGraphVisible = workspace.state.nodeGraphVisible;
  $: documentTabLabels = portfolio.state.documents.map(
    (doc: FrontendDocumentDetails) => {
      const name = doc.displayName;

      if (!editor.instance.inDevelopmentMode()) return { name };

      const tooltip = `Document ID ${doc.id}`;
      return { name, tooltip };
    }
  );
  $: {
    scrollIntoView(activeDocumentIndex);
  }
  function scrollIntoView(index: number) {
    documentPanel?.scrollTabIntoView(index);
  }

  // inject: ["workspace", "portfolio", "dialog", "editor"],

  function resizePanel(e: PointerEvent) {
    const gutter = (e.target || undefined) as HTMLDivElement | undefined;
    const nextSibling = (gutter?.nextElementSibling || undefined) as
      | HTMLDivElement
      | undefined;
    const prevSibling = (gutter?.previousElementSibling || undefined) as
      | HTMLDivElement
      | undefined;
    const parentElement = (gutter?.parentElement || undefined) as
      | HTMLDivElement
      | undefined;

    const nextSiblingName = (nextSibling?.getAttribute(
      "data-subdivision-name"
    ) || undefined) as keyof typeof PANEL_SIZES;
    const prevSiblingName = (prevSibling?.getAttribute(
      "data-subdivision-name"
    ) || undefined) as keyof typeof PANEL_SIZES;

    if (
      !gutter ||
      !nextSibling ||
      !prevSibling ||
      !parentElement ||
      !nextSiblingName ||
      !prevSiblingName
    )
      return;

    // Are we resizing horizontally?
    const isHorizontal = gutter.getAttribute("data-gutter-horizontal") !== null;

    // Get the current size in px of the panels being resized and the gutter
    const gutterSize = isHorizontal
      ? gutter.getBoundingClientRect().width
      : gutter.getBoundingClientRect().height;
    const nextSiblingSize = isHorizontal
      ? nextSibling.getBoundingClientRect().width
      : nextSibling.getBoundingClientRect().height;
    const prevSiblingSize = isHorizontal
      ? prevSibling.getBoundingClientRect().width
      : prevSibling.getBoundingClientRect().height;
    const parentElementSize = isHorizontal
      ? parentElement.getBoundingClientRect().width
      : parentElement.getBoundingClientRect().height;

    // Measure the resizing panels as a percentage of all sibling panels
    const totalResizingSpaceOccupied =
      gutterSize + nextSiblingSize + prevSiblingSize;
    const proportionBeingResized =
      totalResizingSpaceOccupied / parentElementSize;

    // Prevent cursor flicker as mouse temporarily leaves the gutter
    gutter.setPointerCapture(e.pointerId);

    const mouseStart = isHorizontal ? e.clientX : e.clientY;

    const updatePosition = (e: PointerEvent): void => {
      const mouseCurrent = isHorizontal ? e.clientX : e.clientY;
      let mouseDelta = mouseStart - mouseCurrent;

      mouseDelta =
        Math.max(nextSiblingSize + mouseDelta, MIN_PANEL_SIZE) -
        nextSiblingSize;
      mouseDelta =
        prevSiblingSize -
        Math.max(prevSiblingSize - mouseDelta, MIN_PANEL_SIZE);

      panelSizes[nextSiblingName] =
        ((nextSiblingSize + mouseDelta) / totalResizingSpaceOccupied) *
        proportionBeingResized *
        100;
      panelSizes[prevSiblingName] =
        ((prevSiblingSize - mouseDelta) / totalResizingSpaceOccupied) *
        proportionBeingResized *
        100;

      window.dispatchEvent(new CustomEvent("resize"));
    };

    const cleanup = (e: PointerEvent): void => {
      gutter.releasePointerCapture(e.pointerId);

      document.removeEventListener("pointermove", updatePosition);
      document.removeEventListener("pointerleave", cleanup);
      document.removeEventListener("pointerup", cleanup);
    };

    document.addEventListener("pointermove", updatePosition);
    document.addEventListener("pointerleave", cleanup);
    document.addEventListener("pointerup", cleanup);
  }
</script>

<LayoutRow class="workspace" data-workspace>
  <LayoutRow
    class="workspace-grid-subdivision"
    styles={{ "flex-grow": panelSizes["root"] }}
    data-subdivision-name="root"
  >
    <LayoutCol
      class="workspace-grid-subdivision"
      styles={{ "flex-grow": panelSizes["content"] }}
      data-subdivision-name="content"
    >
      <LayoutRow
        class="workspace-grid-subdivision"
        styles={{ "flex-grow": panelSizes["document"] }}
        data-subdivision-name="document"
      >
        <Panel
          panelType={portfolio.state.documents.length > 0
            ? "Document"
            : undefined}
          tabCloseButtons={true}
          tabMinWidths={true}
          tabLabels={documentTabLabels}
          clickAction={(tabIndex) =>
            editor.instance.selectDocument(
              portfolio.state.documents[tabIndex].id
            )}
          closeAction={(tabIndex) =>
            editor.instance.closeDocumentWithConfirmation(
              portfolio.state.documents[tabIndex].id
            )}
          tabActiveIndex={portfolio.state.activeDocumentIndex}
          bind:this={documentPanel}
        />
      </LayoutRow>
      {#if nodeGraphVisible}
        <LayoutRow
          class="workspace-grid-resize-gutter"
          data-gutter-vertical
          on:pointerdown={resizePanel}
        />
        <LayoutRow
          class="workspace-grid-subdivision"
          styles={{ "flex-grow": panelSizes["graph"] }}
          data-subdivision-name="graph"
        >
          <Panel
            panelType="NodeGraph"
            tabLabels={[{ name: "Node Graph" }]}
            tabActiveIndex={0}
          />
        </LayoutRow>
      {/if}
    </LayoutCol>
    <LayoutCol
      class="workspace-grid-resize-gutter"
      data-gutter-horizontal
      on:pointerdown={(e) => resizePanel(e)}
    />
    <LayoutCol
      class="workspace-grid-subdivision"
      styles={{ "flex-grow": panelSizes["details"] }}
      data-subdivision-name="details"
    >
      <LayoutRow
        class="workspace-grid-subdivision"
        styles={{ "flex-grow": panelSizes["properties"] }}
        data-subdivision-name="properties"
      >
        <Panel
          panelType="Properties"
          tabLabels={[{ name: "Properties" }]}
          tabActiveIndex={0}
        />
      </LayoutRow>
      <LayoutRow
        class="workspace-grid-resize-gutter"
        data-gutter-vertical
        on:pointerdown={(e) => resizePanel(e)}
      />
      <LayoutRow
        class="workspace-grid-subdivision"
        styles={{ "flex-grow": panelSizes["layers"] }}
        data-subdivision-name="layers"
      >
        <Panel
          panelType="LayerTree"
          tabLabels={[{ name: "Layer Tree" }]}
          tabActiveIndex={0}
        />
      </LayoutRow>
    </LayoutCol>
  </LayoutRow>
  {#if dialog.state.visible}
    <DialogModal />
  {/if}
</LayoutRow>

<style lang="scss" global>
  .workspace {
    position: relative;
    flex: 1 1 100%;

    .workspace-grid-subdivision {
      min-height: 28px;
      flex: 1 1 0;

      &.folded {
        flex-grow: 0;
        height: 0;
      }
    }

    .workspace-grid-resize-gutter {
      flex: 0 0 4px;

      &.layout-row {
        cursor: ns-resize;
      }

      &.layout-col {
        cursor: ew-resize;
      }
    }
  }
</style>

// frontend/src/components/window/workspace/Workspace.vue
<template>
	<LayoutRow class="workspace" data-workspace>
		<LayoutRow class="workspace-grid-subdivision" :style="{ 'flex-grow': panelSizes['root'] }" data-subdivision-name="root">
			<LayoutCol class="workspace-grid-subdivision" :style="{ 'flex-grow': panelSizes['content'] }" data-subdivision-name="content">
				<LayoutRow class="workspace-grid-subdivision" :style="{ 'flex-grow': panelSizes['document'] }" data-subdivision-name="document">
					<Panel
						:panelType="portfolio.state.documents.length > 0 ? 'Document' : undefined"
						:tabCloseButtons="true"
						:tabMinWidths="true"
						:tabLabels="documentTabLabels"
						:clickAction="(tabIndex: number) => editor.instance.selectDocument(portfolio.state.documents[tabIndex].id)"
						:closeAction="(tabIndex: number) => editor.instance.closeDocumentWithConfirmation(portfolio.state.documents[tabIndex].id)"
						:tabActiveIndex="portfolio.state.activeDocumentIndex"
						ref="documentPanel"
					/>
				</LayoutRow>
				<LayoutRow class="workspace-grid-resize-gutter" data-gutter-vertical @pointerdown="(e: PointerEvent) => resizePanel(e)" v-if="nodeGraphVisible"></LayoutRow>
				<LayoutRow class="workspace-grid-subdivision" v-if="nodeGraphVisible" :style="{ 'flex-grow': panelSizes['graph'] }" data-subdivision-name="graph">
					<Panel :panelType="'NodeGraph'" :tabLabels="[{ name: 'Node Graph' }]" :tabActiveIndex="0" />
				</LayoutRow>
			</LayoutCol>
			<LayoutCol class="workspace-grid-resize-gutter" data-gutter-horizontal @pointerdown="(e: PointerEvent) => resizePanel(e)"></LayoutCol>
			<LayoutCol class="workspace-grid-subdivision" :style="{ 'flex-grow': panelSizes['details'] }" data-subdivision-name="details">
				<LayoutRow class="workspace-grid-subdivision" :style="{ 'flex-grow': panelSizes['properties'] }" data-subdivision-name="properties">
					<Panel :panelType="'Properties'" :tabLabels="[{ name: 'Properties' }]" :tabActiveIndex="0" />
				</LayoutRow>
				<LayoutRow class="workspace-grid-resize-gutter" data-gutter-vertical @pointerdown="(e: PointerEvent) => resizePanel(e)"></LayoutRow>
				<LayoutRow class="workspace-grid-subdivision" :style="{ 'flex-grow': panelSizes['layers'] }" data-subdivision-name="layers">
					<Panel :panelType="'LayerTree'" :tabLabels="[{ name: 'Layer Tree' }]" :tabActiveIndex="0" />
				</LayoutRow>
			</LayoutCol>
		</LayoutRow>
		<DialogModal v-if="dialog.state.visible" />
	</LayoutRow>
</template>

<style lang="scss">
.workspace {
	position: relative;
	flex: 1 1 100%;

	.workspace-grid-subdivision {
		min-height: 28px;
		flex: 1 1 0;

		&.folded {
			flex-grow: 0;
			height: 0;
		}
	}

	.workspace-grid-resize-gutter {
		flex: 0 0 4px;

		&.layout-row {
			cursor: ns-resize;
		}

		&.layout-col {
			cursor: ew-resize;
		}
	}
}
</style>

<script lang="ts">
import { defineComponent } from "vue";

import DialogModal from "@/components/floating-menus/DialogModal.vue";
import LayoutCol from "@/components/layout/LayoutCol.vue";
import LayoutRow from "@/components/layout/LayoutRow.vue";
import Panel from "@/components/window/workspace/Panel.vue";

const MIN_PANEL_SIZE = 100;
const PANEL_SIZES = {
	/**/ root: 100,
	/*   ├── */ content: 80,
	/*   │      ├── */ document: 60,
	/*   │      └── */ graph: 40,
	/*   └── */ details: 20,
	/*          ├── */ properties: 45,
	/*          └── */ layers: 55,
};

export default defineComponent({
	inject: ["workspace", "portfolio", "dialog", "editor"],
	data() {
		return {
			panelSizes: PANEL_SIZES,
		};
	},
	computed: {
		activeDocumentIndex() {
			return this.portfolio.state.activeDocumentIndex;
		},
		nodeGraphVisible() {
			return this.workspace.state.nodeGraphVisible;
		},
		documentTabLabels() {
			return this.portfolio.state.documents.map((doc) => {
				const name = doc.displayName;

				if (!this.editor.instance.inDevelopmentMode()) return { name };

				const tooltip = `Document ID ${doc.id}`;
				return { name, tooltip };
			});
		},
	},
	methods: {
		resizePanel(event: PointerEvent) {
			const gutter = (event.target || undefined) as HTMLDivElement | undefined;
			const nextSibling = (gutter?.nextElementSibling || undefined) as HTMLDivElement | undefined;
			const prevSibling = (gutter?.previousElementSibling || undefined) as HTMLDivElement | undefined;
			const parentElement = (gutter?.parentElement || undefined) as HTMLDivElement | undefined;

			const nextSiblingName = (nextSibling?.getAttribute("data-subdivision-name") || undefined) as keyof typeof PANEL_SIZES;
			const prevSiblingName = (prevSibling?.getAttribute("data-subdivision-name") || undefined) as keyof typeof PANEL_SIZES;

			if (!gutter || !nextSibling || !prevSibling || !parentElement || !nextSiblingName || !prevSiblingName) return;

			// Are we resizing horizontally?
			const isHorizontal = gutter.getAttribute("data-gutter-horizontal") !== null;

			// Get the current size in px of the panels being resized and the gutter
			const gutterSize = isHorizontal ? gutter.getBoundingClientRect().width : gutter.getBoundingClientRect().height;
			const nextSiblingSize = isHorizontal ? nextSibling.getBoundingClientRect().width : nextSibling.getBoundingClientRect().height;
			const prevSiblingSize = isHorizontal ? prevSibling.getBoundingClientRect().width : prevSibling.getBoundingClientRect().height;
			const parentElementSize = isHorizontal ? parentElement.getBoundingClientRect().width : parentElement.getBoundingClientRect().height;

			// Measure the resizing panels as a percentage of all sibling panels
			const totalResizingSpaceOccupied = gutterSize + nextSiblingSize + prevSiblingSize;
			const proportionBeingResized = totalResizingSpaceOccupied / parentElementSize;

			// Prevent cursor flicker as mouse temporarily leaves the gutter
			gutter.setPointerCapture(event.pointerId);

			const mouseStart = isHorizontal ? event.clientX : event.clientY;

			const updatePosition = (event: PointerEvent): void => {
				const mouseCurrent = isHorizontal ? event.clientX : event.clientY;
				let mouseDelta = mouseStart - mouseCurrent;

				mouseDelta = Math.max(nextSiblingSize + mouseDelta, MIN_PANEL_SIZE) - nextSiblingSize;
				mouseDelta = prevSiblingSize - Math.max(prevSiblingSize - mouseDelta, MIN_PANEL_SIZE);

				this.panelSizes[nextSiblingName] = ((nextSiblingSize + mouseDelta) / totalResizingSpaceOccupied) * proportionBeingResized * 100;
				this.panelSizes[prevSiblingName] = ((prevSiblingSize - mouseDelta) / totalResizingSpaceOccupied) * proportionBeingResized * 100;

				window.dispatchEvent(new CustomEvent("resize"));
			};

			const cleanup = (event: PointerEvent): void => {
				gutter.releasePointerCapture(event.pointerId);

				document.removeEventListener("pointermove", updatePosition);
				document.removeEventListener("pointerleave", cleanup);
				document.removeEventListener("pointerup", cleanup);
			};

			document.addEventListener("pointermove", updatePosition);
			document.addEventListener("pointerleave", cleanup);
			document.addEventListener("pointerup", cleanup);
		},
	},
	watch: {
		async activeDocumentIndex(newIndex: number) {
			(this.$refs.documentPanel as typeof Panel | undefined)?.scrollTabIntoView(newIndex);
		},
	},
	components: {
		DialogModal,
		LayoutCol,
		LayoutRow,
		Panel,
	},
});
</script>
