// frontend-svelte/src/components/widgets/WidgetLayout.svelte
<script lang="ts">
	import { isWidgetColumn, isWidgetRow, isWidgetSection, type WidgetLayout } from "@/wasm-communication/messages";

	import WidgetSection from "@/components/widgets/groups/WidgetSection.svelte";
	import WidgetRow from "@/components/widgets/WidgetRow.svelte";

	export let layout: WidgetLayout;
</script>

<!-- TODO: Refactor this component (together with `WidgetRow.svelte`) to be more logically consistent with our layout definition goals, in terms of naming and capabilities -->
<div class="widget-layout">
	{#each layout.layout as layoutGroup, index (index)}
		{#if isWidgetColumn(layoutGroup) || isWidgetRow(layoutGroup)}
			<WidgetRow widgetData={layoutGroup} layoutTarget={layout.layoutTarget} />
		{:else if isWidgetSection(layoutGroup)}
			<WidgetSection widgetData={layoutGroup} layoutTarget={layout.layoutTarget} />
		{:else}
			<span style="color: red">Error: The widget row that belongs here has an invalid layout group type</span>
		{/if}
	{/each}
</div>

<style lang="scss" global>
	.widget-layout {
		height: 100%;
		flex: 0 0 auto;
		display: flex;
		flex-direction: column;
	}
</style>

// frontend-svelte/src/lib/components/widgets/WidgetLayout.vue
<!-- TODO: Refactor this component (together with `WidgetRow.vue`) to be more logically consistent with our layout definition goals, in terms of naming and capabilities -->

<template>
	<div class="widget-layout">
		<component :is="layoutGroupType(layoutRow)" :widgetData="layoutRow" :layoutTarget="layout.layoutTarget" v-for="(layoutRow, index) in layout.layout" :key="index" />
	</div>
</template>

<style lang="scss" global>
.widget-layout {
	height: 100%;
	flex: 0 0 auto;
	display: flex;
	flex-direction: column;
}
</style>

<script lang="ts">


import { isWidgetColumn, isWidgetRow, isWidgetSection, type LayoutGroup, type WidgetLayout } from "@/wasm-communication/messages";

import WidgetSection from "$lib/components/widgets/groups/WidgetSection.svelte";
import WidgetRow from "$lib/components/widgets/WidgetRow.svelte";

export default defineComponent({
	props: {
		layout: { type: Object as PropType<WidgetLayout>, required: true },
	},
	methods: {
		layoutGroupType(layoutRow: LayoutGroup): unknown {
			if (isWidgetColumn(layoutRow)) return WidgetRow;
			if (isWidgetRow(layoutRow)) return WidgetRow;
			if (isWidgetSection(layoutRow)) return WidgetSection;

			throw new Error("Layout row type does not exist");
		},
	},
	components: {
		WidgetRow,
		WidgetSection,
	},
});
</script>
