// frontend/src/components/window/MainWindow.vue
<script lang="ts">
import { defineComponent } from "vue";

import LayoutCol from "@/components/layout/LayoutCol.vue";
import StatusBar from "@/components/window/status-bar/StatusBar.vue";
import TitleBar from "@/components/window/title-bar/TitleBar.vue";
import Workspace from "@/components/window/workspace/Workspace.vue";

export type ApplicationPlatform = "Windows" | "Mac" | "Linux" | "Web";

export default defineComponent({
	data() {
		return {
			platform: "Web" as ApplicationPlatform,
			maximized: true,
		};
	},
	components: {
		LayoutCol,
		StatusBar,
		TitleBar,
		Workspace,
	},
});
</script>

<template>
	<LayoutCol class="main-window">
		<TitleBar :platform="platform" :maximized="maximized" />

		<Workspace />

		<StatusBar />
	</LayoutCol>
</template>

<style lang="scss">
.main-window {
	height: 100%;
	overflow: auto;
	touch-action: none;
}
</style>

// frontend-svelte/src/lib/components/window/MainWindow.svelte
<script lang="ts" context="module">
	export type ApplicationPlatform = "Windows" | "Mac" | "Linux" | "Web";
</script>

<script lang="ts">
	import LayoutCol from "$lib/components/layout/LayoutCol.svelte";
	import StatusBar from "$lib/components/window/status-bar/StatusBar.svelte";
	import TitleBar from "$lib/components/window/title-bar/TitleBar.svelte";
	import Workspace from "$lib/components/window/workspace/Workspace.svelte";

	let platform: ApplicationPlatform = "Web";
	let maximized: true;
</script>

<LayoutCol class="main-window">
	<TitleBar {platform} {maximized} />

	<Workspace />

	<StatusBar />
</LayoutCol>

<style lang="scss" global>
	.main-window {
		height: 100%;
		overflow: auto;
		touch-action: none;
	}
</style>
