// frontend/src/components/widgets/floating-menus/MenuList.vue
<template>
	<FloatingMenu
		class="menu-list"
		v-model:open="isOpen"
		@naturalWidth="(newNaturalWidth: number) => $emit('naturalWidth', newNaturalWidth)"
		:type="'Dropdown'"
		:windowEdgeMargin="0"
		v-bind="{ direction, scrollableY, minWidth }"
		ref="floatingMenu"
		data-hover-menu-keep-open
	>
		<template v-for="(section, sectionIndex) in entries" :key="sectionIndex">
			<Separator :type="'List'" :direction="'Vertical'" v-if="sectionIndex > 0" />
			<LayoutRow
				v-for="(entry, entryIndex) in section"
				:key="entryIndex"
				class="row"
				:class="{ open: isEntryOpen(entry), active: entry.label === activeEntry?.label }"
				@click="() => onEntryClick(entry)"
				@pointerenter="() => onEntryPointerEnter(entry)"
				@pointerleave="() => onEntryPointerLeave(entry)"
			>
				<CheckboxInput v-if="entry.checkbox" v-model:checked="entry.checked" :outlineStyle="true" class="entry-checkbox" />
				<IconLabel v-else-if="entry.icon && drawIcon" :icon="entry.icon" class="entry-icon" />
				<div v-else-if="drawIcon" class="no-icon"></div>

				<span class="entry-label">{{ entry.label }}</span>

				<IconLabel v-if="entry.shortcutRequiresLock && !fullscreen.state.keyboardLocked" :icon="'Info'" :title="keyboardLockInfoMessage" />
				<UserInputLabel v-else-if="entry.shortcut?.length" :inputKeys="[entry.shortcut]" />

				<div class="submenu-arrow" v-if="entry.children?.length"></div>
				<div class="no-submenu-arrow" v-else></div>

				<MenuList
					v-if="entry.children"
					@naturalWidth="(newNaturalWidth: number) => $emit('naturalWidth', newNaturalWidth)"
					:open="entry.ref?.open || false"
					:direction="'TopRight'"
					:entries="entry.children"
					v-bind="{ defaultAction, minWidth, drawIcon, scrollableY }"
					:ref="(ref: typeof FloatingMenu) => ref && (entry.ref = ref)"
				/>
			</LayoutRow>
		</template>
	</FloatingMenu>
</template>

<style lang="scss">
.menu-list {
	.floating-menu-container .floating-menu-content {
		padding: 4px 0;

		.row {
			height: 20px;
			align-items: center;
			white-space: nowrap;
			position: relative;
			flex: 0 0 auto;

			& > * {
				flex: 0 0 auto;
			}

			.entry-icon svg {
				fill: var(--color-e-nearwhite);
			}

			.no-icon {
				width: 16px;
			}

			.entry-label {
				flex: 1 1 100%;
				margin-left: 8px;
			}

			.entry-checkbox,
			.entry-icon,
			.no-icon {
				margin: 0 4px;

				& + .entry-label {
					margin-left: 0;
				}
			}

			.user-input-label {
				margin: 0;
				margin-left: 16px;
			}

			.submenu-arrow {
				width: 0;
				height: 0;
				border-style: solid;
				border-width: 3px 0 3px 6px;
				border-color: transparent transparent transparent var(--color-e-nearwhite);
			}

			.no-submenu-arrow {
				width: 6px;
			}

			.submenu-arrow,
			.no-submenu-arrow {
				margin-left: 6px;
				margin-right: 4px;
			}

			&:hover,
			&.open,
			&.active {
				background: var(--color-6-lowergray);

				&.active {
					background: var(--color-accent);
				}

				svg {
					fill: var(--color-f-white);
				}

				span {
					color: var(--color-f-white);
				}
			}

			&:hover .entry-checkbox label .checkbox-box {
				border: 1px solid var(--color-f-white);

				svg {
					fill: var(--color-f-white);
				}
			}
		}
	}
}
</style>

<script lang="ts">
import { defineComponent, PropType } from "vue";

import { IconName } from "@/utilities/icons";

import LayoutRow from "@/components/layout/LayoutRow.vue";
import FloatingMenu, { MenuDirection } from "@/components/widgets/floating-menus/FloatingMenu.vue";
import CheckboxInput from "@/components/widgets/inputs/CheckboxInput.vue";
import IconLabel from "@/components/widgets/labels/IconLabel.vue";
import UserInputLabel from "@/components/widgets/labels/UserInputLabel.vue";
import Separator from "@/components/widgets/separators/Separator.vue";

export type MenuListEntries<Value = string> = MenuListEntry<Value>[];
export type SectionsOfMenuListEntries<Value = string> = MenuListEntries<Value>[];

interface MenuListEntryData<Value = string> {
	value?: Value;
	label?: string;
	icon?: IconName;
	checkbox?: boolean;
	shortcut?: string[];
	shortcutRequiresLock?: boolean;
	action?: () => void;
	children?: SectionsOfMenuListEntries;
}

export type MenuListEntry<Value = string> = MenuListEntryData<Value> & { ref?: typeof FloatingMenu | typeof MenuList; checked?: boolean };

const KEYBOARD_LOCK_USE_FULLSCREEN = "This hotkey is reserved by the browser, but becomes available in fullscreen mode";
const KEYBOARD_LOCK_SWITCH_BROWSER = "This hotkey is reserved by the browser, but becomes available in Chrome, Edge, and Opera which support the Keyboard.lock() API";

const MenuList = defineComponent({
	inject: ["fullscreen"],
	emits: ["update:open", "update:activeEntry", "naturalWidth"],
	props: {
		entries: { type: Array as PropType<SectionsOfMenuListEntries>, required: true },
		activeEntry: { type: Object as PropType<MenuListEntry>, required: false },
		open: { type: Boolean as PropType<boolean>, required: true },
		direction: { type: String as PropType<MenuDirection>, default: "Bottom" },
		minWidth: { type: Number as PropType<number>, default: 0 },
		drawIcon: { type: Boolean as PropType<boolean>, default: false },
		scrollableY: { type: Boolean as PropType<boolean>, default: false },
		defaultAction: { type: Function as PropType<() => void>, required: false },
	},
	data() {
		return {
			isOpen: this.open,
			keyboardLockInfoMessage: this.fullscreen.keyboardLockApiSupported ? KEYBOARD_LOCK_USE_FULLSCREEN : KEYBOARD_LOCK_SWITCH_BROWSER,
		};
	},
	watch: {
		// Called only when `open` is changed from outside this component (with v-model)
		open(newOpen: boolean) {
			this.isOpen = newOpen;
		},
		isOpen(newIsOpen: boolean) {
			this.$emit("update:open", newIsOpen);
		},
		entries() {
			const floatingMenu = this.$refs.floatingMenu as typeof FloatingMenu;
			floatingMenu.measureAndEmitNaturalWidth();
		},
		drawIcon() {
			const floatingMenu = this.$refs.floatingMenu as typeof FloatingMenu;
			floatingMenu.measureAndEmitNaturalWidth();
		},
	},
	methods: {
		onEntryClick(menuEntry: MenuListEntry): void {
			// Toggle checkbox
			// TODO: This is broken at the moment, fix it when we get rid of using `ref`
			if (menuEntry.checkbox) menuEntry.checked = !menuEntry.checked;

			// Call the action, or a default, if either are provided
			if (menuEntry.action) menuEntry.action();
			else if (this.defaultAction) this.defaultAction();

			// Emit the clicked entry as the new active entry
			this.$emit("update:activeEntry", menuEntry);

			// Close the containing menu
			if (menuEntry.ref) menuEntry.ref.isOpen = false;
			this.$emit("update:open", false);
			this.isOpen = false; // TODO: This is a hack for MenuBarInput submenus, remove it when we get rid of using `ref`
		},
		onEntryPointerEnter(menuEntry: MenuListEntry): void {
			if (!menuEntry.children?.length) return;

			if (menuEntry.ref) menuEntry.ref.isOpen = true;
			else this.$emit("update:open", true);
		},
		onEntryPointerLeave(menuEntry: MenuListEntry): void {
			if (!menuEntry.children?.length) return;

			if (menuEntry.ref) menuEntry.ref.isOpen = false;
			else this.$emit("update:open", false);
		},
		isEntryOpen(menuEntry: MenuListEntry): boolean {
			if (!menuEntry.children?.length) return false;

			return this.open;
		},
	},
	computed: {
		entriesWithoutRefs(): MenuListEntryData[][] {
			return this.entries.map((menuListEntries) =>
				menuListEntries.map((entry) => {
					const { ref, ...entryWithoutRef } = entry;
					return entryWithoutRef;
				})
			);
		},
	},
	components: {
		FloatingMenu,
		Separator,
		IconLabel,
		CheckboxInput,
		UserInputLabel,
		LayoutRow,
	},
});
export default MenuList;
</script>

// frontend-svelte/src/lib/components/floating-menus/MenuList.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";

	import { type MenuListEntry } from "@/wasm-communication/messages";

	import FloatingMenu, { type MenuDirection } from "$lib/components/layout/FloatingMenu.svelte";
	import LayoutCol from "$lib/components/layout/LayoutCol.svelte";
	import LayoutRow from "$lib/components/layout/LayoutRow.svelte";
	import IconLabel from "$lib/components/widgets/labels/IconLabel.svelte";
	import Separator from "$lib/components/widgets/labels/Separator.svelte";
	import TextLabel from "$lib/components/widgets/labels/TextLabel.svelte";
	import UserInputLabel from "$lib/components/widgets/labels/UserInputLabel.svelte";

	let floatingMenu: FloatingMenu;
	let scroller: LayoutCol;

	// emits: ["update:open", "update:activeEntry", "naturalWidth"],

	export let entries: MenuListEntry[][];
	export let activeEntry: MenuListEntry;
	export let open: boolean;
	export let direction: MenuDirection = "Bottom";
	export let minWidth = 0;
	export let drawIcon = false;
	export let interactive = false;
	export let scrollableY = false;
	export let virtualScrollingEntryHeight = 0;
	export let tooltip: string | undefined;

	let isOpen = open;
	let highlighted = activeEntry as MenuListEntry | undefined;
	let virtualScrollingEntriesStart = 0;

	// Called only when `open` is changed from outside this component (with v-model)
	$: watchOpen(open);
	$: createEventDispatcher("update:open", isOpen);
	$: entries, floatingMenu.measureAndEmitNaturalWidth();
	$: drawIcon, floatingMenu.measureAndEmitNaturalWidth();
	$: virtualScrollingTotalHeight = entries[0].length * virtualScrollingEntryHeight;
	$: virtualScrollingStartIndex = Math.floor(virtualScrollingEntriesStart / virtualScrollingEntryHeight);
	$: virtualScrollingEndIndex = Math.min(entries[0].length, virtualScrollingStartIndex + 1 + 400 / virtualScrollingEntryHeight);

	function watchOpen(open: boolean) {
		isOpen = open;
		highlighted = activeEntry;
	}

	export function scrollViewTo(distanceDown: number): void {
		scroller.div().scrollTo(0, distanceDown);
	}

	function onEntryClick(menuListEntry: MenuListEntry): void {
		// Call the action if available
		if (menuListEntry.action) menuListEntry.action();

		// Emit the clicked entry as the new active entry
		createEventDispatcher("update:activeEntry", menuListEntry);

		// Close the containing menu
		if (menuListEntry.ref) menuListEntry.ref.isOpen = false;
		createEventDispatcher("update:open", false);
		isOpen = false; // TODO: This is a hack for MenuBarInput submenus, remove it when we get rid of using `ref`
	}

	function onEntryPointerEnter(menuListEntry: MenuListEntry): void {
		if (!menuListEntry.children?.length) return;

		if (menuListEntry.ref) menuListEntry.ref.isOpen = true;
		else createEventDispatcher("update:open", true);
	}

	function onEntryPointerLeave(menuListEntry: MenuListEntry): void {
		if (!menuListEntry.children?.length) return;

		if (menuListEntry.ref) menuListEntry.ref.isOpen = false;
		else createEventDispatcher("update:open", false);
	}

	function isEntryOpen(menuListEntry: MenuListEntry): boolean {
		if (!menuListEntry.children?.length) return false;

		return open;
	}

	/// Handles keyboard navigation for the menu. Returns if the entire menu stack should be dismissed
	function keydown(e: KeyboardEvent, submenu: boolean): boolean {
		// Interactive menus should keep the active entry the same as the highlighted one
		if (interactive) highlighted = activeEntry;

		const menuOpen = isOpen;
		const flatEntries = entries.flat().filter((entry) => !entry.disabled);
		const openChild = flatEntries.findIndex((entry) => entry.children?.length && entry.ref?.isOpen);

		const openSubmenu = (highlighted: MenuListEntry): void => {
			if (highlighted.ref && highlighted.children?.length) {
				highlighted.ref.isOpen = true;

				// Highlight first item
				highlighted.ref.setHighlighted(highlighted.children[0][0]);
			}
		};

		if (!menuOpen && (e.key === " " || e.key === "Enter")) {
			// Allow opening menu with space or enter
			isOpen = true;
			highlighted = activeEntry;
		} else if (menuOpen && openChild >= 0) {
			// Redirect the keyboard navigation to a submenu if one is open
			const shouldCloseStack = flatEntries[openChild].ref?.keydown(e, true);

			// Highlight the menu item in the parent list that corresponds with the open submenu
			if (e.key !== "Escape" && highlighted) setHighlighted(flatEntries[openChild]);

			// Handle the child closing the entire menu stack
			if (shouldCloseStack) {
				isOpen = false;
				return true;
			}
		} else if ((menuOpen || interactive) && (e.key === "ArrowUp" || e.key === "ArrowDown")) {
			// Navigate to the next and previous entries with arrow keys

			let newIndex = e.key === "ArrowUp" ? flatEntries.length - 1 : 0;
			if (highlighted) {
				const index = highlighted ? flatEntries.map((entry) => entry.label).indexOf(highlighted.label) : 0;
				newIndex = index + (e.key === "ArrowUp" ? -1 : 1);

				// Interactive dropdowns should lock at the end whereas other dropdowns should loop
				if (interactive) newIndex = Math.min(flatEntries.length - 1, Math.max(0, newIndex));
				else newIndex = (newIndex + flatEntries.length) % flatEntries.length;
			}

			const newEntry = flatEntries[newIndex];
			setHighlighted(newEntry);
		} else if (menuOpen && e.key === "Escape") {
			// Close menu with escape key
			isOpen = false;

			// Reset active to before open
			setHighlighted(activeEntry);
		} else if (menuOpen && highlighted && e.key === "Enter") {
			// Handle clicking on an option if enter is pressed
			if (!highlighted.children?.length) onEntryClick(highlighted);
			else openSubmenu(highlighted);

			// Stop the event from triggering a press on a new dialog
			e.preventDefault();

			// Enter should close the entire menu stack
			return true;
		} else if (menuOpen && highlighted && e.key === "ArrowRight") {
			// Right arrow opens a submenu
			openSubmenu(highlighted);
		} else if (menuOpen && e.key === "ArrowLeft") {
			// Left arrow closes a submenu
			if (submenu) isOpen = false;
		}

		// By default, keep the menu stack open
		return false;
	}

	function setHighlighted(newHighlight: MenuListEntry | undefined) {
		highlighted = newHighlight;
		// Interactive menus should keep the active entry the same as the highlighted one
		if (interactive && newHighlight?.value !== activeEntry?.value) createEventDispatcher("update:activeEntry", newHighlight);
	}

	function onScroll(e: Event) {
		if (!virtualScrollingEntryHeight) return;
		virtualScrollingEntriesStart = (e.target as HTMLElement)?.scrollTop || 0;
	}
</script>

<FloatingMenu
	class="menu-list"
	open={isOpen}
	on:open={(state) => (isOpen = state)}
	on:naturalWidth={(newNaturalWidth) => createEventDispatcher("naturalWidth", newNaturalWidth)}
	type="Dropdown"
	windowEdgeMargin={0}
	escapeCloses={false}
	{direction}
	scrollableY={scrollableY && virtualScrollingEntryHeight === 0}
	{minWidth}
	bind:this={floatingMenu}
>
	<!-- If we put the scrollableY on the layoutcol for non-font dropdowns then for some reason it always creates a tiny scrollbar.
	However when we are using the virtual scrolling then we need the layoutcol to be scrolling so we can bind the events without using $refs. -->
	<LayoutCol
		bind:this={scroller}
		scrollableY={scrollableY && virtualScrollingEntryHeight !== 0}
		on:scroll={onScroll}
		styles={{ "min-width": virtualScrollingEntryHeight ? `${minWidth}px` : `inherit` }}
	>
		{#if virtualScrollingEntryHeight}
			<LayoutRow class="scroll-spacer" styles={{ height: `${virtualScrollingStartIndex * virtualScrollingEntryHeight}px` }} />
		{/if}
		{#each entries as section, sectionIndex (sectionIndex)}
			{#if sectionIndex > 0}
				<Separator type="List" direction="Vertical" />
			{/if}
			{#each virtualScrollingEntryHeight ? section.slice(virtualScrollingStartIndex, virtualScrollingEndIndex) : section as entry, entryIndex (entryIndex + (virtualScrollingEntryHeight ? virtualScrollingStartIndex : 0))}
				<LayoutRow
					class="row"
					classes={{ open: isEntryOpen(entry), active: entry.label === highlighted?.label, disabled: entry.disabled }}
					styles={{ height: virtualScrollingEntryHeight || "20px" }}
					title={tooltip}
					on:click={() => !entry.disabled && onEntryClick(entry)}
					on:pointerenter={() => !entry.disabled && onEntryPointerEnter(entry)}
					on:pointerleave={() => !entry.disabled && onEntryPointerLeave(entry)}
				>
					{#if entry.icon && drawIcon}
						<IconLabel icon={entry.icon} class="entry-icon" />
					{:else if drawIcon}
						<div class="no-icon" />
					{/if}

					{#if entry.font}
						<link rel="stylesheet" href={entry.font?.toString()} />
					{/if}

					<TextLabel class="entry-label" styles={{ "font-family": `${!entry.font ? "inherit" : entry.value}` }}>{entry.label}</TextLabel>

					{#if entry.shortcut?.keys.length}
						<UserInputLabel keysWithLabelsGroups={[entry.shortcut.keys]} requiresLock={entry.shortcutRequiresLock} />
					{/if}

					{#if entry.children?.length}
						<div class="submenu-arrow" />
					{:else}
						<div class="no-submenu-arrow" />
					{/if}

					{#if entry.children}
						<svelte:self
							on:naturalWidth={(newNaturalWidth) => createEventDispatcher("naturalWidth", newNaturalWidth)}
							open={entry.ref?.open || false}
							direction="TopRight"
							entries={entry.children}
							{minWidth}
							{drawIcon}
							{scrollableY}
							bind:this={entry.ref}
						/>
					{/if}
				</LayoutRow>
			{/each}
		{/each}
		{#if virtualScrollingEntryHeight}
			<LayoutRow class="scroll-spacer" styles={{ height: `${virtualScrollingTotalHeight - virtualScrollingEndIndex * virtualScrollingEntryHeight}px` }} />
		{/if}
	</LayoutCol>
</FloatingMenu>

<style lang="scss" global>
	.menu-list {
		.floating-menu-container .floating-menu-content {
			padding: 4px 0;

			.separator div {
				background: var(--color-4-dimgray);
			}

			.scroll-spacer {
				flex: 0 0 auto;
			}

			.row {
				height: 20px;
				align-items: center;
				white-space: nowrap;
				position: relative;
				flex: 0 0 auto;

				& > * {
					flex: 0 0 auto;
				}

				.entry-icon svg {
					fill: var(--color-e-nearwhite);
				}

				.no-icon {
					width: 16px;
				}

				.entry-label {
					flex: 1 1 100%;
					margin-left: 8px;
				}

				.entry-icon,
				.no-icon {
					margin: 0 4px;

					& + .entry-label {
						margin-left: 0;
					}
				}

				.user-input-label {
					margin-left: 16px;
				}

				.submenu-arrow {
					width: 0;
					height: 0;
					border-style: solid;
					border-width: 3px 0 3px 6px;
					border-color: transparent transparent transparent var(--color-e-nearwhite);
				}

				.no-submenu-arrow {
					width: 6px;
				}

				.submenu-arrow,
				.no-submenu-arrow {
					margin-left: 6px;
					margin-right: 4px;
				}

				&:hover,
				&.open {
					background: var(--color-6-lowergray);
					color: var(--color-f-white);

					.entry-icon svg {
						fill: var(--color-f-white);
					}
				}

				&.active {
					background: var(--color-e-nearwhite);
					color: var(--color-2-mildblack);

					.entry-icon svg {
						fill: var(--color-2-mildblack);
					}
				}

				&.disabled {
					color: var(--color-8-uppergray);

					&:hover {
						background: none;
					}

					svg {
						fill: var(--color-8-uppergray);
					}
				}
			}
		}
	}
</style>
