// frontend-svelte/src/lib/components/layout/LayoutRow.svelte
<script lang="ts">
  let className = "";
  export { className as class };
  export let classes: Record<string, boolean> = {};
  let styleName = "";
  export { styleName as style };
  export let styles: Record<string, string | number> = {};
  export let tooltip: string | undefined = undefined;
  export let scrollableX: boolean = false;
  export let scrollableY: boolean = false;

  $: extraClasses = Object.entries(classes)
    .flatMap((classAndState) => (classAndState[1] ? [classAndState[0]] : []))
    .join(" ");
  $: extraStyles = Object.entries(styles)
    .map((styleAndValue) => `${styleAndValue[0]}: ${styleAndValue[1]};`)
    .join(" ");
</script>

<div
  class={`layout-row ${className} ${extraClasses}`.trim()}
  class:scrollable-x={scrollableX}
  class:scrollable-y={scrollableY}
  style={`${styleName} ${extraStyles}`.trim()}
  title={tooltip}
  on:click
  on:pointerdown
  {...$$restProps}
>
  <slot />
</div>

<style lang="scss" global>
  .layout-row {
    display: flex;
    flex-direction: row;
    flex-grow: 1;
  }
</style>

// frontend/src/components/layout/LayoutRow.vue
<template>
	<div
		class="layout-row"
		:class="{ 'scrollable-x': scrollableX, 'scrollable-y': scrollableY }"
		:data-scrollable-x="scrollableX || undefined"
		:data-scrollable-y="scrollableY || undefined"
		:title="tooltip"
	>
		<slot></slot>
	</div>
</template>

<style lang="scss">
.layout-row {
	display: flex;
	flex-direction: row;
	flex-grow: 1;

	.spacer {
		flex: 1 1 100%;
	}
}
</style>

<script lang="ts">
import { defineComponent, type PropType } from "vue";

export default defineComponent({
	props: {
		scrollableX: { type: Boolean as PropType<boolean>, default: false },
		scrollableY: { type: Boolean as PropType<boolean>, default: false },
		tooltip: { type: String as PropType<string | undefined>, required: false },
	},
});
</script>
