// frontend/src/components/window/title-bar/WindowButtonsWindows.svelte
<script lang="ts">
	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import IconLabel from "@/components/widgets/labels/IconLabel.svelte";

	export let maximized = false;
</script>

<LayoutRow class="window-button windows minimize" tooltip="Minimize">
	<IconLabel icon={"WindowButtonWinMinimize"} />
</LayoutRow>
{#if !maximized}
	<LayoutRow class="window-button windows maximize" tooltip="Maximize">
		<IconLabel icon={"WindowButtonWinMaximize"} />
	</LayoutRow>
{:else}
	<LayoutRow class="window-button windows restore-down" tooltip="Restore Down">
		<IconLabel icon={"WindowButtonWinRestoreDown"} />
	</LayoutRow>
{/if}
<LayoutRow class="window-button windows close" tooltip="Close">
	<IconLabel icon={"WindowButtonWinClose"} />
</LayoutRow>

<style lang="scss" global>
	.window-button.windows {
		flex: 0 0 auto;
		align-items: center;
		padding: 0 17px;

		svg {
			fill: var(--color-e-nearwhite);
		}

		&:hover {
			background: var(--color-6-lowergray);

			svg {
				fill: var(--color-f-white);
			}
		}

		&.close:hover {
			background: #e81123;
		}
	}
</style>

// client/web/src/components/window/title-bar/WindowButtonsWindows.vue
<template>
	<div class="windows window-button minimize" title="Minimize">
		<Icon :icon="'WindowButtonWinMinimize'" />
	</div>
	<div class="windows window-button maximize" title="Maximize" v-if="!maximized">
		<Icon :icon="'WindowButtonWinMaximize'" />
	</div>
	<div class="windows window-button restore-down" title="Restore Down" v-if="maximized">
		<Icon :icon="'WindowButtonWinRestoreDown'" />
	</div>
	<div class="windows window-button close" title="Close">
		<Icon :icon="'WindowButtonWinClose'" />
	</div>
</template>

<style lang="scss">
.windows.window-button {
	display: flex;
	align-items: center;
	padding: 0 17px;

	svg {
		fill: var(--color-e-nearwhite);
	}

	&:hover {
		background: var(--color-6-lowergray);

		svg {
			fill: var(--color-f-white);
		}
	}

	&.close:hover {
		background: #e81123;
	}
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import Icon from "@/components/widgets/labels/Icon.vue";

export default defineComponent({
	components: { Icon },
	props: {
		maximized: { type: Boolean, default: false },
	},
});
</script>
