// frontend-svelte/src/components/widgets/inputs/OptionalInput.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";

	import { type IconName } from "@/utility-functions/icons";

	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import CheckboxInput from "@/components/widgets/inputs/CheckboxInput.svelte";

	// emits: ["update:checked"],

	export let checked: boolean;
	export let disabled = false;
	export let icon: IconName = "Checkmark";
	export let tooltip: string | undefined = undefined;
</script>

<LayoutRow class="optional-input" classes={{ disabled }}>
	<CheckboxInput {checked} {disabled} on:input={(e) => createEventDispatcher("update:checked", e.target.checked)} {icon} {tooltip} />
</LayoutRow>

<style lang="scss" global>
	.optional-input {
		flex-grow: 0;

		label {
			align-items: center;
			justify-content: center;
			white-space: nowrap;
			width: 24px;
			height: 24px;
			border: 1px solid var(--color-5-dullgray);
			border-radius: 2px 0 0 2px;
			box-sizing: border-box;
		}

		&.disabled label {
			border: 1px solid var(--color-4-dimgray);
		}
	}
</style>

// client/web/src/components/widgets/inputs/OptionalInput.vue
<template>
	<div class="optional-input">
		<CheckboxInput :checked="checked" @input="(e) => $emit('update:checked', e.target.checked)" :icon="icon" />
	</div>
</template>

<style lang="scss">
.optional-input {
	label {
		display: flex;
		align-items: center;
		white-space: nowrap;
		justify-content: center;
		width: 24px;
		height: 24px;
		border: 1px solid var(--color-7-middlegray);
		border-radius: 2px 0 0 2px;
		box-sizing: border-box;

		&:hover {
			background: var(--color-6-lowergray);
		}
	}

	input:checked + label {
		border: 1px solid var(--color-accent);

		&:hover {
			border: 1px solid var(--color-accent-hover);
			background: none;
		}
	}
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import CheckboxInput from "@/components/widgets/inputs/CheckboxInput.vue";

export default defineComponent({
	props: {
		checked: { type: Boolean, required: true },
		icon: { type: String, default: "Checkmark" },
	},
	components: {
		CheckboxInput,
	},
});
</script>
