// frontend-svelte/src/components/layout/LayoutCol.svelte
<script lang="ts">
	let className = "";
	export { className as class };
	export let classes: Record<string, boolean> = {};
	let styleName = "";
	export { styleName as style };
	export let styles: Record<string, string | number | undefined> = {};
	export let tooltip: string | undefined = undefined;
	export let scrollableX: boolean = false;
	export let scrollableY: boolean = false;

	let divElement: HTMLDivElement;

	$: extraClasses = Object.entries(classes)
		.flatMap((classAndState) => (classAndState[1] ? [classAndState[0]] : []))
		.join(" ");
	$: extraStyles = Object.entries(styles)
		.flatMap((styleAndValue) => (styleAndValue[1] !== undefined ? [`${styleAndValue[0]}: ${styleAndValue[1]};`] : []))
		.join(" ");

	export function div(): HTMLDivElement {
		return divElement;
	}
</script>

<div
	class={`layout-col ${className} ${extraClasses}`.trim()}
	class:scrollable-x={scrollableX}
	class:scrollable-y={scrollableY}
	style={`${styleName} ${extraStyles}`.trim()}
	title={tooltip}
	bind:this={divElement}
	on:click
	on:dblclick
	on:pointerdown
	on:pointermove
	on:pointerup
	on:dragleave
	on:dragover
	on:dragstart
	on:dragend
	on:drop
	on:wheel
	on:scroll
	on:focus
	on:blur
	{...$$restProps}
>
	<slot />
</div>

<style lang="scss" global>
	.layout-col {
		display: flex;
		flex-direction: column;
		flex-grow: 1;
	}
</style>

// frontend-svelte/src/lib/layout/LayoutCol.vue
	<!-- <div
		class="layout-col"
		:class="{ 'scrollable-x': scrollableX, 'scrollable-y': scrollableY }"
		:data-scrollable-x="scrollableX || undefined"
		:data-scrollable-y="scrollableY || undefined"
		:title="tooltip"
	>
		<slot></slot>
	</div>

<style lang="scss">
.layout-col {
	display: flex;
	flex-direction: column;
	flex-grow: 1;

	.spacer {
		flex: 1 1 100%;
	}
}
</style>

<script lang="ts">
import { defineComponent, type PropType } from "vue";

export default defineComponent({
	props: {
		scrollableX: { type: Boolean as PropType<boolean>, default: false },
		scrollableY: { type: Boolean as PropType<boolean>, default: false },
		tooltip: { type: String as PropType<string | undefined>, required: false },
	},
});
</script> -->
