// frontend/src/components/window/title-bar/WindowButtonsWindows.svelte
<script lang="ts">
	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import IconLabel from "@/components/widgets/labels/IconLabel.svelte";

	export let maximized = false;
</script>

<LayoutRow class="window-button windows minimize" tooltip="Minimize">
	<IconLabel icon={"WindowButtonWinMinimize"} />
</LayoutRow>
{#if !maximized}
	<LayoutRow class="window-button windows maximize" tooltip="Maximize">
		<IconLabel icon={"WindowButtonWinMaximize"} />
	</LayoutRow>
{:else}
	<LayoutRow class="window-button windows restore-down" tooltip="Restore Down">
		<IconLabel icon={"WindowButtonWinRestoreDown"} />
	</LayoutRow>
{/if}
<LayoutRow class="window-button windows close" tooltip="Close">
	<IconLabel icon={"WindowButtonWinClose"} />
</LayoutRow>

<style lang="scss" global>
	.window-button.windows {
		flex: 0 0 auto;
		align-items: center;
		padding: 0 17px;

		svg {
			fill: var(--color-e-nearwhite);
		}

		&:hover {
			background: var(--color-6-lowergray);

			svg {
				fill: var(--color-f-white);
			}
		}

		&.close:hover {
			background: #e81123;
		}
	}
</style>

// web-frontend/src/components/window/title-bar/WindowButtonsWindows.vue
<template>
	<div class="windows window-button minimize" title="Minimize">
		<svg width="10" height="10" viewBox="0 0 10 10">
			<rect y="4" width="10" height="1" />
		</svg>
	</div>
	<div class="windows window-button maximize" title="Maximize" v-if="!maximized">
		<svg width="10" height="10" viewBox="0 0 10 10">
			<path d="M10,0v10H0V0H10z M9,1H1v8h8V1z" />
		</svg>
	</div>
	<div class="windows window-button restore-down" title="Restore Down" v-if="maximized">
		<svg width="10" height="10" viewBox="0 0 10 10">
			<path d="M10,8H8v2H0V2h2V0h8V8z M7,3H1v6h6V3z M9,1H3v1h5v5h1V1z" />
		</svg>
	</div>
	<div class="windows window-button close" title="Close">
		<svg width="10" height="10" viewBox="0 0 10 10">
			<polygon points="10,0.7 9.3,0 5,4.3 0.7,0 0,0.7 4.3,5 0,9.3 0.7,10 5,5.7 9.3,10 10,9.3 5.7,5" />
		</svg>
	</div>
</template>

<style lang="scss">
.windows.window-button {
	display: flex;
	align-items: center;
	padding: 0 20px;

	svg {
		fill: #ddd;
	}

	&:hover {
		background: #555;

		svg {
			fill: #fff;
		}
	}

	&.close:hover {
		background: #e81123;
	}
}
</style>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
	props: {
		maximized: { type: Boolean, default: false },
	},
});
</script>
