// frontend-svelte/src/components/window/status-bar/StatusBar.svelte
<script lang="ts">
	import { getContext, onMount } from "svelte";

	import { platformIsMac } from "@/utility-functions/platform";
	import { type HintData, type HintInfo, type LayoutKeysGroup, UpdateInputHints } from "@/wasm-communication/messages";

	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import Separator from "@/components/widgets/labels/Separator.svelte";
	import UserInputLabel from "@/components/widgets/labels/UserInputLabel.svelte";
	import { type Editor } from "@/wasm-communication/editor";

	const editor = getContext<Editor>("editor");

	let hintData: HintData[] = [];

	function inputKeysForPlatform(hint: HintInfo): LayoutKeysGroup[] {
		if (platformIsMac() && hint.keyGroupsMac) return hint.keyGroupsMac;
		return hint.keyGroups;
	}

	onMount(() => {
		editor.subscriptions.subscribeJsMessage(UpdateInputHints, (updateInputHints) => {
			hintData = updateInputHints.hintData;
		});
	});
</script>

<LayoutRow class="status-bar">
	<LayoutRow class="hint-groups">
		{#each hintData as hintGroup, index (hintGroup)}
			{#if index !== 0}
				<Separator type={"Section"} />
			{/if}
			{#each hintGroup as hint (hint)}
				{#if hint.plus}
					<LayoutRow class="plus">+</LayoutRow>
				{/if}
				<UserInputLabel mouseMotion={hint.mouse} keysWithLabelsGroups={inputKeysForPlatform(hint)}>{hint.label}</UserInputLabel>
			{/each}
		{/each}
	</LayoutRow>
</LayoutRow>

<style lang="scss" global>
	.status-bar {
		height: 24px;
		width: 100%;
		flex: 0 0 auto;

		.hint-groups {
			flex: 0 0 auto;
			max-width: 100%;
			margin: 0 -4px;
			overflow: hidden;

			.separator.section {
				margin: 0;
			}

			.plus {
				flex: 0 0 auto;
				align-items: center;
				font-weight: 700;
			}

			.user-input-label {
				margin: 0 8px;

				& + .user-input-label {
					margin-left: 0;
				}
			}
		}
	}
</style>

// client/web/src/components/window/status-bar/StatusBar.vue
<template>
	<div class="status-bar">
		<UserInputLabel :inputMouse="'LMB'">Select Object</UserInputLabel>
		<span class="plus">+</span>
		<UserInputLabel :inputKeys="['⇧']">Grow/Shrink Selection</UserInputLabel>
		<div class="divider"></div>
		<UserInputLabel :inputMouse="'LMBDrag'">Select Area</UserInputLabel>
		<span class="plus">+</span>
		<UserInputLabel :inputKeys="['⇧']">Grow/Shrink Selection</UserInputLabel>
		<div class="divider"></div>
		<UserInputLabel :inputKeys="['G']">Grab Selected</UserInputLabel>
		<UserInputLabel :inputKeys="['R']">Rotate Selected</UserInputLabel>
		<UserInputLabel :inputKeys="['S']">Scale Selected</UserInputLabel>
		<div class="divider"></div>
		<UserInputLabel :inputKeys="['↑', '→', '↓', '←']">Nudge Selected</UserInputLabel>
		<span class="plus">+</span>
		<UserInputLabel :inputKeys="['⇧']">Big Increment Nudge</UserInputLabel>
		<div class="divider"></div>
		<UserInputLabel :inputKeys="['Alt']" :inputMouse="'LMBDrag'">Move Duplicate</UserInputLabel>
		<UserInputLabel :inputKeys="['Ctrl', 'D']">Duplicate</UserInputLabel>
	</div>
</template>

<style lang="scss">
.status-bar {
	display: flex;
}

.plus {
	display: flex;
	align-items: center;
	font-weight: bold;
}

.divider {
	width: 1px;
	height: 16px;
	margin: 4px 0;
	background: #888;
}

.user-input-label + .user-input-label {
	margin-left: 0;
}
</style>

<script lang="ts">
import { defineComponent } from "vue";
import UserInputLabel from "../../widgets/labels/UserInputLabel.vue";

export default defineComponent({
	components: {
		UserInputLabel,
	},
});
</script>
