// frontend/src/components/widgets/inputs/ColorInput.vue
<template>
	<LayoutRow class="color-input" :title="tooltip">
		<button :class="{ none: value.none }" :style="{ '--chosen-color': value.toHexOptionalAlpha() }" @click="() => $emit('update:open', true)" tabindex="0" data-floating-menu-spawner>
			<TextLabel :bold="true" class="chip" v-if="chip">{{ chip }}</TextLabel>
		</button>
		<ColorPicker v-model:open="isOpen" :color="value" @update:color="(color: Color) => colorPickerUpdated(color)" :allowNone="true" />
	</LayoutRow>
</template>

<style lang="scss">
.color-input {
	box-sizing: border-box;
	position: relative;
	border: 1px solid var(--color-5-dullgray);
	border-radius: 2px;
	padding: 1px;

	> button {
		position: relative;
		overflow: hidden;
		border: none;
		padding: 0;
		margin: 0;
		width: 100%;
		height: 100%;
		border-radius: 1px;

		&::before {
			content: "";
			position: absolute;
			width: 100%;
			height: 100%;
			padding: 2px;
			top: -2px;
			left: -2px;
			background: linear-gradient(var(--chosen-color), var(--chosen-color)), var(--color-transparent-checkered-background);
			background-size: var(--color-transparent-checkered-background-size);
			background-position: var(--color-transparent-checkered-background-position);
		}

		&.none {
			background: var(--color-none);
			background-repeat: var(--color-none-repeat);
			background-position: var(--color-none-position);
			background-size: var(--color-none-size-24px);
			background-image: var(--color-none-image-24px);
		}

		.chip {
			position: absolute;
			bottom: -1px;
			right: 0;
			height: 13px;
			line-height: 13px;
			background: var(--color-f-white);
			color: var(--color-2-mildblack);
			border-radius: 4px 0 0 0;
			padding: 0 4px;
			font-size: 10px;
			box-shadow: 0 0 2px var(--color-3-darkgray);
		}
	}

	&.color-input.color-input > button {
		outline-offset: 0;
	}

	> .floating-menu {
		left: 50%;
		bottom: 0;
	}
}
</style>

<script lang="ts">
import { defineComponent, type PropType } from "vue";

import { Color } from "@/wasm-communication/messages";

import ColorPicker from "@/components/floating-menus/ColorPicker.vue";
import LayoutRow from "@/components/layout/LayoutRow.vue";
import TextLabel from "@/components/widgets/labels/TextLabel.vue";

export default defineComponent({
	emits: ["update:value", "update:open"],
	props: {
		value: { type: Color as PropType<Color>, required: true },
		noTransparency: { type: Boolean as PropType<boolean>, default: false }, // TODO: Rename to allowTransparency, also implement allowNone
		disabled: { type: Boolean as PropType<boolean>, default: false },
		tooltip: { type: String as PropType<string | undefined>, required: false },

		// Bound through `v-model`
		// TODO: See if this should be made to follow the pattern of DropdownInput.vue so this could be removed
		open: { type: Boolean as PropType<boolean>, required: true },
	},
	data() {
		return {
			isOpen: false,
		};
	},
	watch: {
		// Called only when `open` is changed from outside this component (with v-model)
		open(newOpen: boolean) {
			this.isOpen = newOpen;
		},
		isOpen(newIsOpen: boolean) {
			this.$emit("update:open", newIsOpen);
		},
	},
	methods: {
		colorPickerUpdated(color: Color) {
			this.$emit("update:value", color);
		},
	},
	computed: {
		chip() {
			return undefined;
		},
	},
	components: {
		ColorPicker,
		LayoutRow,
		TextLabel,
	},
});
</script>

// frontend/src/components/widgets/inputs/ColorInput.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";

	import type { FillChoice } from "@graphite/messages";
	import { Color, contrastingOutlineFactor, Gradient } from "@graphite/messages";

	import ColorPicker from "@graphite/components/floating-menus/ColorPicker.svelte";
	import LayoutCol from "@graphite/components/layout/LayoutCol.svelte";
	import TextLabel from "@graphite/components/widgets/labels/TextLabel.svelte";

	const dispatch = createEventDispatcher<{ value: FillChoice; startHistoryTransaction: undefined }>();

	let open = false;

	export let value: FillChoice;
	export let disabled = false;
	export let readOnly = false;
	export let allowNone = false;
	// export let allowTransparency = false; // TODO: Implement
	export let tooltip: string | undefined = undefined;

	$: outlineFactor = contrastingOutlineFactor(value, ["--color-1-nearblack", "--color-3-darkgray"], 0.01);
	$: outlined = outlineFactor > 0.0001;
	$: chosenGradient = value instanceof Gradient ? value.toLinearGradientCSS() : `linear-gradient(${value.toHexOptionalAlpha()}, ${value.toHexOptionalAlpha()})`;
	$: none = value instanceof Color ? value.none : false;
	$: transparency = value instanceof Gradient ? value.stops.some((stop) => stop.color.alpha < 1) : value.alpha < 1;
</script>

<LayoutCol class="color-button" classes={{ open, disabled, none, transparency, outlined }} {tooltip}>
	<button {disabled} style:--chosen-gradient={chosenGradient} style:--outline-amount={outlineFactor} on:click={() => (open = true)} tabindex="0" data-floating-menu-spawner>
		{#if disabled && value instanceof Color && !value.none}
			<TextLabel>sRGB</TextLabel>
		{/if}
	</button>
	<ColorPicker
		{open}
		{readOnly}
		on:open={({ detail }) => (open = detail)}
		colorOrGradient={value}
		on:colorOrGradient={({ detail }) => {
			value = detail;
			dispatch("value", detail);
		}}
		on:startHistoryTransaction={() => {
			// This event is sent to the backend so it knows to start a transaction for the history system. See discussion for some explanation:
			// <https://github.com/GraphiteEditor/Graphite/pull/1584#discussion_r1477592483>
			dispatch("startHistoryTransaction");
		}}
		{allowNone}
	/>
</LayoutCol>

<style lang="scss" global>
	.color-button {
		position: relative;
		min-width: 80px;

		> button {
			border: none;
			border-radius: 2px;
			padding: 0;
			margin: 0;
			width: 100%;
			height: 100%;
			overflow: hidden;
			position: relative;

			&::before {
				content: "";
				position: absolute;
				top: 0;
				bottom: 0;
				left: 0;
				right: 0;
				background: var(--chosen-gradient);
			}

			.text-label {
				background: var(--color-5-dullgray);
				font-size: 10px;
				line-height: 12px;
				height: 12px;
				border-radius: 0 0 0 2px;
				padding-right: 4px;
				padding-left: 4px;
				position: absolute;
				right: 0;
				top: 0;
			}
		}

		&.outlined > button::after {
			content: "";
			position: absolute;
			top: 0;
			bottom: 0;
			left: 0;
			right: 0;
			box-shadow: inset 0 0 0 1px rgba(var(--color-5-dullgray-rgb), var(--outline-amount));
		}

		&.transparency > button {
			background-image: var(--color-transparent-checkered-background);
			background-size: var(--color-transparent-checkered-background-size);
			background-position: var(--color-transparent-checkered-background-position);
			background-repeat: var(--color-transparent-checkered-background-repeat);
		}

		&:not(.disabled).none > button {
			background: var(--color-none);
			background-repeat: var(--color-none-repeat);
			background-position: var(--color-none-position);
			background-size: var(--color-none-size-24px);
			background-image: var(--color-none-image-24px);
		}

		&.disabled.none > button::after {
			content: "";
			position: absolute;
			top: 0;
			bottom: 0;
			left: 0;
			right: 0;
			background: var(--color-4-dimgray);
		}

		&:not(.disabled):hover > button .text-label,
		&:not(.disabled).open > button .text-label {
			background: var(--color-6-lowergray);
			color: var(--color-f-white);
		}

		&.disabled > button .text-label {
			background: var(--color-4-dimgray);
			color: var(--color-8-uppergray);
		}

		> .floating-menu {
			left: 50%;
			bottom: 0;
		}
	}
</style>
