// frontend-svelte/src/components/widgets/inputs/OptionalInput.svelte
<script lang="ts">
	import { createEventDispatcher } from "svelte";

	import { type IconName } from "@/utility-functions/icons";

	import LayoutRow from "@/components/layout/LayoutRow.svelte";
	import CheckboxInput from "@/components/widgets/inputs/CheckboxInput.svelte";

	// emits: ["update:checked"],

	export let checked: boolean;
	export let disabled = false;
	export let icon: IconName = "Checkmark";
	export let tooltip: string | undefined = undefined;
</script>

<LayoutRow class="optional-input" classes={{ disabled }}>
	<CheckboxInput {checked} {disabled} on:input={(e) => createEventDispatcher("update:checked", e.target.checked)} {icon} {tooltip} />
</LayoutRow>

<style lang="scss" global>
	.optional-input {
		flex-grow: 0;

		label {
			align-items: center;
			justify-content: center;
			white-space: nowrap;
			width: 24px;
			height: 24px;
			border: 1px solid var(--color-5-dullgray);
			border-radius: 2px 0 0 2px;
			box-sizing: border-box;
		}

		&.disabled label {
			border: 1px solid var(--color-4-dimgray);
		}
	}
</style>

// frontend/src/components/widgets/inputs/OptionalInput.vue
<template>
	<LayoutRow class="optional-input">
		<CheckboxInput :checked="checked" @input="(e: Event) => $emit('update:checked', (e.target as HTMLInputElement).checked)" :icon="icon" :tooltip="tooltip" />
	</LayoutRow>
</template>

<style lang="scss">
.optional-input {
	flex-grow: 0;

	label {
		align-items: center;
		justify-content: center;
		white-space: nowrap;
		width: 24px;
		height: 24px;
		border: 1px solid var(--color-7-middlegray);
		border-radius: 2px 0 0 2px;
		box-sizing: border-box;

		&:hover {
			background: var(--color-6-lowergray);
		}
	}

	input:checked + label {
		border: 1px solid var(--color-accent);

		&:hover {
			border: 1px solid var(--color-accent-hover);
			background: none;
		}
	}
}
</style>

<script lang="ts">
import { defineComponent, type PropType } from "vue";

import { type IconName } from "@/utility-functions/icons";

import LayoutRow from "@/components/layout/LayoutRow.vue";
import CheckboxInput from "@/components/widgets/inputs/CheckboxInput.vue";

export default defineComponent({
	emits: ["update:checked"],
	props: {
		checked: { type: Boolean as PropType<boolean>, required: true },
		icon: { type: String as PropType<IconName>, default: "Checkmark" },
		tooltip: { type: String as PropType<string | undefined>, required: false },
	},
	components: {
		CheckboxInput,
		LayoutRow,
	},
});
</script>
