// frontend/src/components/widgets/labels/TextLabel.vue
<template>
	<span class="text-label" :class="{ bold, italic, multiline, 'table-align': tableAlign }" :style="minWidth > 0 ? `min-width: ${minWidth}px` : ''" :title="tooltip">
		<slot></slot>
	</span>
</template>

<style lang="scss">
.text-label {
	line-height: 18px;
	white-space: nowrap;

	&.bold {
		font-weight: 700;
	}

	&.italic {
		font-style: italic;
	}

	&.multiline {
		white-space: pre-wrap;
		margin: 4px 0;
	}

	&.table-align {
		flex: 0 0 30%;
		text-align: right;
	}
}
</style>

<script lang="ts">
import { defineComponent, type PropType } from "vue";

export default defineComponent({
	props: {
		bold: { type: Boolean as PropType<boolean>, default: false },
		italic: { type: Boolean as PropType<boolean>, default: false },
		tableAlign: { type: Boolean as PropType<boolean>, default: false },
		minWidth: { type: Number as PropType<number>, default: 0 },
		multiline: { type: Boolean as PropType<boolean>, default: false },
		tooltip: { type: String as PropType<string | undefined>, required: false },
	},
});
</script>

// frontend-svelte/src/components/widgets/labels/TextLabel.svelte
<script lang="ts">
	let className = "";
	export { className as class };
	export let classes: Record<string, boolean> = {};
	export let disabled = false;
	export let bold = false;
	export let italic = false;
	export let tableAlign = false;
	export let minWidth = 0;
	export let multiline = false;
	export let tooltip: string | undefined = undefined;

	$: extraClasses = Object.entries(classes)
		.flatMap((classAndState) => (classAndState[1] ? [classAndState[0]] : []))
		.join(" ");
</script>

<span
	class={`text-label ${className} ${extraClasses}`.trim()}
	class:disabled
	class:bold
	class:italic
	class:multiline
	class:table-align={tableAlign}
	style:min-width={minWidth > 0 ? `${minWidth}px` : undefined}
	title={tooltip}
>
	<slot />
</span>

<style lang="scss" global>
	.text-label {
		line-height: 18px;
		white-space: nowrap;
		// Force Safari to not draw a text cursor, even though this element has `user-select: none`
		cursor: default;

		&.disabled {
			color: var(--color-8-uppergray);
		}

		&.bold {
			font-weight: 700;
		}

		&.italic {
			font-style: italic;
		}

		&.multiline {
			white-space: pre-wrap;
			margin: 4px 0;
		}

		&.table-align {
			flex: 0 0 30%;
			text-align: right;
		}
	}
</style>
