// frontend/src/components/window/title-bar/WindowTitle.svelte
<script lang="ts">
	import LayoutRow from "@graphite/components/layout/LayoutRow.svelte";
	import TextLabel from "@graphite/components/widgets/labels/TextLabel.svelte";

	export let text: string;
</script>

<LayoutRow class="window-title">
	<TextLabel>{text}</TextLabel>
</LayoutRow>

<style lang="scss" global>
	.window-title {
		flex: 0 0 auto;
		align-items: center;
		white-space: nowrap;
		padding: 0 8px;
	}
</style>

// web-frontend/src/components/header/WindowTitle.vue
<template>
	<div class="window-title">
		<span>X-35B.gdd* - Graphite</span>
	</div>
</template>

<style lang="scss">
.window-title {
	display: flex;
	align-items: center;
	white-space: nowrap;
	padding: 0 8px;
}
</style>

<script lang="ts">
import { Options, Vue } from "vue-class-component";

@Options({
	components: {},
	props: {},
})
export default class WindowTitle extends Vue {}
</script>
