// web-frontend/src/components/layout/LayoutCol.vue
<template>
	<div :class="['layout-col']">
		<slot></slot>
	</div>
</template>

<style lang="scss">
.layout-col {
	display: flex;
	flex-direction: column;
	flex-grow: 1;
}
</style>

<script lang="ts">
import { Options, Vue } from "vue-class-component";

@Options({
	components: {},
	props: {},
})
export default class LayoutCol extends Vue {}
</script>

// frontend-svelte/src/lib/components/layout/LayoutCol.svelte
<script lang="ts">
  export let tooltip: string | undefined = undefined;

  let className = "";
  export { className as class };
  export let scrollableX: boolean = false;
  export let scrollableY: boolean = false;
</script>

<div
  class={`layout-col ${className}`}
  class:scrollable-x={scrollableX}
  class:scrollable-y={scrollableY}
  title={tooltip}
>
  <slot />
</div>

<style lang="scss">
  @import "./_layout.scss";
  .layout-col {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
  }
</style>
